### ISSUE TITLE
Please contact me

### ISSUE THREAD

**Issue by Holiaaa** [cmmiller26/Turf-Wars#4]
Hi!
I seen a video about a Roblox project you made (it was an Animal Crossing clone with an inventory and some tools you made in roblox like the original game) and i want to contact you about this project!
We are really interested about how you made that, we started making roblox game and we fall in love with your system (really haha)
If you have discord please contact me : Daylowww or if send me an email at this adress : jonathanferry452@gmail.com

have a good day :D

**Comment by cmmiller26** [comment]
Sorry but I no longer have access to this project, if you still wish to contact me please do so on the Roblox Developer Forum or on discord (@snarlyzoo)
